import express from 'express';
import { mediaRouter } from './MediaRouter';
import { authRouter } from './AuthRouter';
import { resumeRouter } from './ResumeRouter';
import { userRouter } from './UserRouter';
import { tailoredResumeRouter } from './TailoredResumeRouter';
import { coverLetterRouter } from './CoverLetterRouter';
import { paymentSubscriptionRouter } from './PaymentSubscriptionRouter';
import { jobRouter } from './JobRouter';
import { jobStreamRouter } from './JobStreamRouter';
import { aiAnalyticsRouter } from './AIAnalyticsRouter';
import { applicationTrackerRouter } from './ApplicationTrackerRouter';
const v1Router = express.Router();

v1Router.use('/media', mediaRouter);
v1Router.use('/auth', authRouter);
v1Router.use('/resume', resumeRouter);
v1Router.use('/tailored-resume', tailoredResumeRouter);
v1Router.use('/user', userRouter);
v1Router.use('/cover-letter', coverLetterRouter);
v1Router.use('/payment-subscription', paymentSubscriptionRouter);
v1Router.use('/jobs', jobRouter);
v1Router.use('/jobs', jobStreamRouter);
v1Router.use('/ai', aiAnalyticsRouter);
v1Router.use('/application-tracker', applicationTrackerRouter);
export { v1Router };
